os: osx
language: c++
before_install:
  - brew update
  - brew bundle
  - brew uninstall libjpeg --ignore-dependencies # wrong libjpeg version can cause us problems
  - sed -i -- 's/Cellar\/sdl2\/2.0.8\//Cellar\/sdl2\/2.0.9\//g' EndlessSky.xcodeproj/project.pbxproj # Fix SDL2 path (brew supplies 2.0.9, ES by default looks for 2.0.8)
  - git config --local user.name "MCOfficer"
  - git config --local user.email "mcofficer@gmx.de"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
script: 
  - xcodebuild
  - cd build/Release/Endless\ Sky.app/Contents/MacOS/
  - install_name_tool -change /usr/local/opt/libpng/lib/libpng16.16.dylib @executable_path/../Frameworks/libpng16.16.dylib Endless\ Sky
  - install_name_tool -change /usr/local/opt/mad/lib/libmad.0.2.1.dylib @executable_path/../Frameworks/libmad.0.2.1.dylib Endless\ Sky
  - install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib @executable_path/../Frameworks/libSDL2-2.0.0.dylib Endless\ Sky
  - install_name_tool -change /usr/local/opt/jpeg-turbo/lib/libturbojpeg.0.dylib @executable_path/../Frameworks/libturbojpeg.0.dylib Endless\ Sky
before_deploy:
  - zip EndlessSky-Nightly-Binary.zip -9 Endless\ Sky
  - cd ../../../
  - zip EndlessSky-Nightly-Full.zip -r9 Endless\ Sky.app/
deploy:
  provider: releases
  api_key:
    secure: oeWF9bGh/XLblRF898te7S3kFaK9XYMRTa70XFXdXtHbfP8x+Y18Ted2paxVHxLOWTjYFdiWREr8qaoxO94w8e0B4ncu5YXG1XoyNH2AzuNEXUllyJ1kL6B4M5Wo9kHudaNBYE9NHTSyJ4T0PvTVDHj5JhzHjNKq53KMLcyPImwZjyYDl/yrNBO6H5cvhEs8yib78QKWf17GePyEk/xlcR8RjEsimjEdTLf5DbsL6eHfNXfROFWVzIuG5qMwz/RAPWcsaDlpx9uBmwuNSpM2NwGd88FVXcE/FQaeShpfIgxrt0Vlzs+RsH/dX7S7We/dfiT1ypxiDHfRkGayl20ymn29gLeWV8kuTWYl+mbQj92qarWLtJKAA3IkAe8grb4ICfW7WB7btjlhIqc9yS+WMCOPcJgzoc5jCcYL2z3VOLpSdXHK3153yhIDpO6MmkKSrrbHfj1h5Zz8KARLLFehYUMpblC06tLtsoaZAUnbNBBmGrBSmK6+i7jT1NXrKBS5MBVygIaBOc0Hji2Pz9G59QZvG0/t8UX9YQXfJklOdzypnM49Idv95khJuCS8iqNqCKBunyzPISQMXDGGrPMBMudwoHAJ6OXgKB7ZqykWWyiRIp7JWx6AKSeZ8OXVx1eR8/Cv45npRH4ILOk/U9RYjF6ORQGrvwWUfE2QlxBs4wc=
  file:
    - EndlessSky-Nightly-Full.zip
    - Endless\ Sky.app/Contents/MacOS/EndlessSky-Nightly-Binary.zip
  skip_cleanup: true
  on:
    repo: ES-Builds/endless-sky-osx
    tags: true

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
